server:
  port: 9001

#  rootdir文件上传根路径  linux:/xxx/xx/ window D:\Download\
#  tempdir: 分片临时目录
#  isDelTempFile   和片后是否删除临时目录
spring:
  uploader:
    rootdir: D:\Download\
    tempdir: temp
    isDelTempFile: true




