server:
  port: 9001

spring:
  uploader:
    type: unc
    account:
    pwd:
    tempdir: temp
    isDelTempFile: true


# 文件上传根路径  linux
#fileUploadPath: /xxx/xx/
# 文件上传根路径  window
fileUploadPath: D:\Download\